services:
  - type: web
    name: elephantcare-pdfviewer
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /pdf/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
